import {useState} from 'react';
import ClientHeader from './ClientHeader';
import ClientFooter from './ClientFooter';
import '../../styles/client/ClientContent/ClientLegal.scss';

const Legal = () => {

    const [showTermsAndCond, setShowTermsAndCond] = useState<boolean>(true);

    document.title = 'Lipky.by. Политики сайта';

    return (
        <>
        <ClientHeader/>
        <section className='legal-container'>
            <div className='legal-header'>
                <div className='legal-header__headline'>
                    <span>наши политики</span>
                </div>
                <div className='legal-header__btns'>
                    <div className='btn-container'>
                        <button onClick={() => setShowTermsAndCond(true)}
                            disabled={showTermsAndCond}
                            className={showTermsAndCond ? `btn-selected` : `btn`}
                        >Условия использования</button>
                    </div>
                    <div className='btn-container'>
                        <button onClick={() => setShowTermsAndCond(false)}
                            disabled={!showTermsAndCond}
                            className={!showTermsAndCond ? `btn-selected` : `btn`}
                        >Политика конфиденциальности</button>
                    </div>
                </div>
            </div>
            {showTermsAndCond ?
                <div className={'legal-selected-text'}>
                    <h1>Условия использованяи сайта</h1>
                    <p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur earum eius esse eveniet, exercitationem explicabo facere ipsam itaque molestiae nam nobis numquam obcaecati, officia omnis, perspiciatis ratione recusandae rerum unde.</span><span>Cupiditate magnam quibusdam quo saepe, sequi sunt? A ab alias autem, commodi deserunt dolorem eaque ex fugit, illum, inventore maxime necessitatibus non nulla porro reprehenderit saepe tempore temporibus ut vero.</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta ex minus odio perferendis provident. A ad alias consectetur cum dolores ea, incidunt ipsum, iste maxime, odit quaerat quas quisquam repellat.</span><span>Ad alias aliquid assumenda atque beatae consectetur culpa dicta dolores est excepturi facere fugit id itaque laborum magnam maiores molestias nesciunt non officia, repellat reprehenderit sequi sunt temporibus ullam ut.</span></span>
                    </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam et labore laboriosam nulla qui quidem quo quod repellat, rerum ut? Aliquid ex, impedit itaque laborum necessitatibus odit sed velit voluptas.</span><span>Consequatur, delectus dolore eius impedit laboriosam minima nobis perspiciatis possimus praesentium quisquam sint velit, vero voluptates? Atque autem cupiditate dignissimos distinctio explicabo nesciunt nisi, nobis officiis praesentium sunt suscipit, vitae.</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque aut cum cumque dicta doloremque eligendi esse eveniet iste laborum modi mollitia, neque nobis porro praesentium reprehenderit sit ullam veniam. Eaque!</span><span>Accusantium ad aliquam asperiores assumenda autem corporis cum debitis, deserunt dolore est et excepturi exercitationem expedita facilis inventore laborum libero magni non porro quibusdam quos temporibus, voluptates voluptatibus. A, enim!</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab cupiditate distinctio doloremque earum error ipsam magnam officiis? Accusamus at autem dolore dolorem earum harum laboriosam, maiores possimus quam vero voluptatum?</span><span>Adipisci aliquam doloremque earum excepturi fugiat in labore maxime necessitatibus, pariatur, quos similique velit voluptatem? Corporis dolores ea ipsa modi optio quibusdam sit velit veniam. Esse iure molestiae officiis praesentium!</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A beatae blanditiis cupiditate, dicta eum ex exercitationem explicabo fugiat harum incidunt inventore ipsam ipsum laudantium maiores odit pariatur, quaerat quasi soluta.</span><span>Aliquam atque blanditiis dicta dolore ea, esse facere incidunt magni modi mollitia natus nemo non officia omnis perferendis praesentium quas quis sed similique soluta, temporibus totam ullam ut veniam voluptatibus!</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque eaque et illum iure, iusto, libero molestiae, nam nisi perferendis quo veritatis voluptas voluptates! Accusantium animi at, eos fugiat illum praesentium.</span><span>Amet consequuntur, dicta distinctio, dolores doloribus dolorum eveniet explicabo minima neque optio praesentium quo recusandae reiciendis repellat unde? Eum fugit iusto quo similique tempora. Aperiam laudantium magni possimus veniam veritatis.</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, dicta nam necessitatibus nemo nihil numquam odio provident sit? Ad dicta eius error, fugiat id ipsum labore officia quaerat saepe unde!</span><span>Adipisci consequatur cumque dolore eveniet facilis illum ipsam ipsum libero, mollitia, natus necessitatibus nobis odio officiis porro praesentium sint unde voluptatem? Dolorem dolorum error exercitationem fuga ipsum laboriosam nemo, sequi.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid dolor dolores eius, esse id in laboriosam odio pariatur praesentium quibusdam similique, sint suscipit voluptate! Eius exercitationem harum perferendis provident quis.</span><span>Dolore eveniet excepturi illum incidunt ipsum maiores nam repellat repellendus sed tenetur? Doloribus eligendi esse facilis ipsa iusto laborum necessitatibus neque omnis. Ducimus eligendi nam optio placeat quos sint vero.</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam dignissimos doloribus eos et facilis ipsam iusto obcaecati officia repellendus rerum! Accusamus at distinctio earum ipsum minus possimus quam recusandae sint!</span><span>Amet assumenda autem cupiditate earum eos explicabo, impedit labore maiores minima nemo non obcaecati odio officiis quas rem totam, voluptatem. Consequuntur dignissimos error laboriosam laudantium officia? Ducimus provident ut veniam!</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium alias culpa dolor dolorem dolorum eos, ex harum impedit labore necessitatibus neque nobis numquam, odit optio perferendis unde veniam? Magni.</span><span>Molestiae mollitia sapiente soluta! Amet aut, blanditiis error esse fugiat laudantium libero repellat sequi tempore vitae! Architecto deleniti dolorem ducimus earum illum maiores nobis quaerat quidem, tempore temporibus totam voluptatum?</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aspernatur assumenda, consequatur dicta dolores ea eos excepturi harum incidunt laudantium mollitia nam necessitatibus nihil numquam porro, quae saepe sint soluta.</span><span>Debitis eveniet illo quos rem veritatis. Ab animi cum dignissimos, dolor dolores ea esse in ipsum maiores non perferendis possimus quae quaerat, reprehenderit sequi similique vel veniam voluptate voluptates, voluptatibus?</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias architecto autem deleniti distinctio ducimus excepturi ipsa ipsam neque omnis placeat provident quidem quis, repellendus temporibus ullam unde, veniam! Accusantium!</span><span>Ab aliquam dolorem eligendi minima nam, natus odio praesentium provident quos repellendus sequi similique tempora veniam! Aliquam, architecto asperiores dolores facilis fugiat, hic iure iusto maiores praesentium, quia quibusdam voluptatum!</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cupiditate ducimus et eveniet expedita fugit maxime neque odio officia pariatur praesentium quasi qui recusandae sapiente sed similique velit vitae, voluptatum?</span><span>Aliquam blanditiis deserunt distinctio doloribus, eius ex exercitationem explicabo fuga inventore itaque maxime modi nihil quo quod recusandae reprehenderit similique, sit tempore ullam vel veritatis, vero voluptas voluptates? Laudantium, nobis.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aperiam beatae dolorum eaque eos fugit illum modi nisi provident velit? Dolore error expedita, laudantium magnam natus voluptate. Culpa, labore, sed?</span><span>A cumque dicta dignissimos dolorum minima necessitatibus odio qui quos recusandae vero! Blanditiis deleniti enim esse facere fugiat illo, in molestias nobis quo quos repellendus similique tempore! Laboriosam, sit, voluptatibus.</span></span><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad blanditiis corporis dignissimos eos error esse incidunt minima nihil pariatur praesentium qui recusandae repellendus reprehenderit, sapiente, similique sunt ullam, voluptate?</span><span>Ab beatae esse libero nisi, nulla quasi! Aliquam aliquid autem culpa doloremque, dolorum eum, ex facere hic id minus nulla numquam pariatur placeat quasi quibusdam quo quod sapiente voluptas. Vitae.</span></span>
                </p>
                </div>

                :
                
                <div className='legal-selected-text'>
                    <h1>Политика конфиденциальности</h1>
                    <p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque iure maxime modi quisquam vero? Culpa dolore dolorum eveniet hic illo necessitatibus nisi, recusandae ut voluptatibus! Dolore facilis hic perferendis? Doloribus?</span><span>Aliquid at culpa dignissimos doloribus ducimus eum exercitationem laudantium modi, nam officiis optio praesentium quos ratione sapiente sit temporibus tenetur veritatis voluptatum. Ab animi illo minus molestias optio veniam, voluptatibus.</span></span>
                    </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad atque beatae consequatur ea eum, explicabo impedit nisi praesentium quae quas reprehenderit voluptas? Aliquid deserunt dolor hic ipsam non sapiente!</span><span>Accusamus dolorum ex fuga temporibus. Dicta magni quae tempora vel. Adipisci autem blanditiis commodi consectetur cupiditate dolore eius eum exercitationem ipsum, nostrum odio quibusdam quis sed similique sint tenetur vel!</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci architecto culpa earum eius excepturi expedita facere minus nobis praesentium quod! Amet doloribus explicabo in, nostrum possimus saepe sint veniam vitae?</span><span>Amet asperiores autem ea esse illo in, itaque laudantium molestiae mollitia odit optio porro provident quasi reiciendis repellendus, velit veritatis voluptatibus. Ad dolorum magni molestias, nostrum numquam sed suscipit vero.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad aliquid animi beatae, consectetur excepturi fugit ipsam itaque laboriosam, laudantium minima modi nisi quaerat repellat, sit tenetur totam vel vero?</span><span>Ad commodi harum ipsam ipsum nihil, odit possimus quidem tempora vel voluptates? Consectetur eum hic illo incidunt itaque minus obcaecati odio, quaerat vel voluptates! A architecto eius molestiae non praesentium?</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem consectetur minima odio tenetur vitae. A asperiores consequuntur ea ex facilis id laborum numquam pariatur quae ullam! Eligendi reiciendis, sapiente. Praesentium!</span><span>Alias, aspernatur deserunt, fugiat neque nesciunt omnis possimus provident quidem quis sint unde veniam, vitae. Accusamus corporis cupiditate deserunt, ducimus, eveniet facere harum id ipsam praesentium quam soluta, ut veniam.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur consectetur cumque, dolorem et excepturi impedit iste itaque laboriosam nemo neque, nobis odit officiis pariatur sit tenetur totam vitae! Deserunt, suscipit?</span><span>Ab aliquid blanditiis, cum ducimus ea enim esse est eveniet exercitationem harum in ipsam mollitia natus nesciunt nihil non nostrum omnis pariatur placeat provident qui quis ut vel, velit voluptatibus.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque est fugit iste laborum porro quia, quod similique sunt. Autem distinctio, doloribus expedita officiis porro quisquam sunt tempora unde veritatis voluptatem!</span><span>Nisi, nobis quas? Aspernatur explicabo nulla perspiciatis similique veniam! Alias ipsum repellendus reprehenderit! Adipisci consequatur itaque obcaecati porro quam! Deserunt doloribus eum explicabo magnam molestias natus repellat voluptatem? Dolore, nobis?</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquam amet deleniti eum ex explicabo facilis fugit in, modi, molestiae nihil non nostrum odit placeat quaerat rem sit ullam velit!</span><span>Architecto dignissimos dolorem impedit incidunt maiores molestias nobis quae quia, repudiandae similique tempora ullam voluptate voluptatibus. Adipisci blanditiis consectetur, consequatur deleniti eligendi, in iste minus officia, quo quod vitae voluptate!</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias aperiam aspernatur, consectetur deserunt doloremque dolorum ea est eum fuga inventore labore obcaecati officia porro praesentium quia ratione rem vitae.</span><span>Commodi dolorem eveniet ex, id nam omnis recusandae sunt tempore voluptatum. Adipisci culpa delectus dicta, et explicabo fuga inventore iusto modi nisi, non quae quas quo reprehenderit sed similique veniam.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam aperiam architecto assumenda dolorem doloremque, et itaque labore nemo quidem quos repellat reprehenderit temporibus. Culpa doloremque dolorum maiores minima unde vel.</span><span>Corporis deserunt dolore dolorem doloribus maiores minus officiis pariatur rem similique soluta. Ad asperiores commodi debitis doloremque dolorum ducimus eum fugiat incidunt magni nihil obcaecati, omnis quos saepe ut veniam?</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, expedita, nulla! Cum dicta natus quis! Accusantium ad debitis earum eligendi eveniet minima modi mollitia nobis, officiis quasi repellendus rerum voluptatibus!</span><span>A esse laudantium perferendis. Ab, beatae blanditiis consequatur debitis distinctio dolor doloribus eligendi fugit ipsum, minima modi nesciunt obcaecati officia omnis qui repellendus sunt ullam unde vel voluptate. Quis, voluptates.</span></span>
                </p><p><span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam assumenda cumque deleniti doloribus dolorum eaque expedita facilis illo, labore libero natus nisi odit quasi recusandae rem velit veritatis voluptatibus voluptatum.</span><span>Accusantium asperiores cum eos esse ex exercitationem facere fuga impedit ipsum iste iusto minus molestias nam nemo non omnis, perferendis perspiciatis quaerat quo quod ratione reiciendis unde vitae! Expedita, voluptas!</span></span>
                </p>
                </div>
            }
        </section>
        <ClientFooter/>
        </>

    );
};

export default Legal;